version: "3.9"

services:
  app:
    build: .
    container_name: docsage-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/docsage
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PORT=5000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server/uploads:/app/server/uploads

  worker:
    build: .
    container_name: docsage-worker
    command: ["node", "server/worker.js"]
    environment:
      - MONGO_URL=mongodb://mongo:27017/docsage
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server/uploads:/app/server/uploads

  mongo:
    image: mongo:7
    container_name: docsage-mongo-compose
    ports:
      - "27018:27017"
    volumes:
      - docsage-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: docsage-redis-compose
    ports:
      - "6380:6379"

volumes:
  docsage-mongo-data: